name: Linters

on: push

env:
  FORCE_COLOR: 1

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Setup ESLint
        run: |
          yarn add -D eslint eslint-plugin-nuxt
          -f .eslintrc.json
      - name: ESLint Report
        run: npx eslint .
